### ISSUE TITLE
Error in dependencies

### ISSUE THREAD

**Issue by GoldGamerPT** [yallurium/supaquiz#1]
![image](https://github.com/yallurium/supaquiz/assets/75499273/9322a250-0bd5-4915-8fd1-202477eaba4f)

**Comment by yallurium** [comment]
To make this work locally, add a `secrets.dart` file with the two constants `supabaseUrl` and `supabaseAnonKey`, either pointing to your local Supabase instance or your own one. The file is `.gitignore`'d as it's sensitive info, but I'll add an example file to the repo and mention this step in the README.

**Comment by GoldGamerPT** [comment]
when i create the game it appears this:
![image](https://github.com/yallurium/supaquiz/assets/75499273/f66c52c2-6351-4e85-87b6-4a3e61a93407)
